version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: transcripts
    ports:
      - "5432:5432"
  app:
    build: .
    environment:
      DB_URL: postgresql+psycopg2://user:pass@db:5432/transcripts
    depends_on:
      - db
    command: ["python", "-m", "meeting_summerizer.main"]
